### ISSUE TITLE
suggestion for key binding method

### ISSUE THREAD

**Issue by ghost** [DonCanjas/mpv-webp-generator#2]
Right now, the script explicitly holds 4 sets of key bindings.
That is a bit too much (especially when the user is using a lot of different scripts).

I suggest doing what some other scripts do, which is have 1 key binding to activate the script, and then the script is activated, temporarily "hijack" or set key bindings for the rest of the functionality, and then release those key bindings after the script has been deactivated.

for example:
Shift+w activates and deactivates the script

OSD shows:
```
Webp gen:
1	start	00:00:00:000
2	end	00:00:00:000
w	Generate webp
s	Generate webp w/ sub
```

So the keys 1, 2, w, s only interact with the script when it is activated and showing on screen.
For en example of another script that works this way, see: [Webm Converter](https://github.com/ekisu/mpv-webm)

ps. Generating with or without subtitle doesn't really need to be different functions, can just check if subtitle has been set to visible or not inside MPV

**Comment by DonCanjas** [comment]
I am not interested in doing the method you suggested, although I understand your concern.
